name: Generate Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run asset generation script
        run: bun generateAssets.js

      - name: Check for changes
        id: git_status
        run: |
          if git diff --exit-code; then
            echo "NO_CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "NO_CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push generated assets
        if: steps.git_status.outputs.NO_CHANGES == 'false'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "[WORKFLOW]: Generated assets"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}